# Generated by Django 4.0.5 on 2022-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=500)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
