# Generated by Django 4.0.5 on 2022-07-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='pup_date',
        ),
    ]
